name: clvision-challenge
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cloudpickle
  - cudatoolkit
  - cycler
  - cytoolz
  - dask-core
  - dbus
  - decorator
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - geos
  - gettext
  - giflib
  - glib
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - imageio
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jasper
  - jedi
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lame
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - liblapack
  - liblapacke
  - libllvm9
  - libopencv
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libxcb
  - libxkbcommon
  - libxml2
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - networkx
  - ninja
  - nspr
  - nss
  - numpy
  - numpy-base
  - olefile
  - opencv
  - openh264
  - openssl
  - pandas
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - py-opencv
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - sip
  - six
  - sqlite
  - tk
  - toolz
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - wheel
  - x264
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
    - albumentations
    - efficientnet-pytorch
    - imgaug
    - opencv-python-headless
    - pyqt5-sip
    - pyqtwebengine

