parameters:
  scenario: nic
  sub_dir: nic
  cls: dense_freeze_till3
  method: task_mem
  n_classes: 50
  #Augmentation
  aug: True
  aug_type: center_224
  #replay
  replay_examples: 200
  replay_used: 600
  replay_epochs: 1
  #review
  review_lr_factor: 1
  review_size: 20000
  review_epoch: 1
  #train
  batch_size: 32
  epochs: 1
  optimizer: SGD
  nesterov: True
  momentum: 0
  weight_decay: 0.001
  lr: 0.01
  #misc
  preload_data: False
  use_cuda: True
